### ISSUE TITLE
current 3D-DNA version

### ISSUE THREAD

**Issue by dustin-cram** [theaidenlab/3d-dna#170]
Hi,

I want to confirm that I am using the latest version of 3D-DNA because there seem to be three different versions reported in different places.  I downloaded from the release link on the github page titled "3D-DNA Phasing branch 201008" (https://github.com/aidenlab/3d-dna/releases/tag/201008).

But if I run 'run-asm-pipeline.sh --help' the first line of output gives a different version: 
'version: 190716'
and just below that there is yet another version:
3D de novo assembly: version 170123

I am concerned because the options available in the version I downloaded don't match the documentation in the DNAZoo manual or many of these posts.  For example the DNAZoo manual says there should be an option '-m, --merge', but in my version '-m' is mode and must be diploid or haploid.  And there are several other issues and forum posts that refer to a '--build-gapped-map' option which is required to output the 'FINAL' files.  But if I use that option with my version, I get a warning message: 
":| WARNING: Unknown option. Ignoring: --build-gapped-map"
and no FINAL output files are produced.

Can you please let me know which version I should be using, and how I can convince it to produce the 'FINAL' files?

Regards,

Dustin Cram
I

**Comment by dudcha** [comment]
Hey Dustin,

Valid question. The version you are using is the latest one, associated with Hoencamp et al., 2021 Science paper and what we run internally at the DNA Zoo. Indeed the versioning is confusing. I apologize for that: since the edits to this release mostly concerned the phasing part, the assembly script per se has not changed since July 2019 (hence the 190716). Basically different pieces of the script have their own version tracking and I should clean this up. The DNA Zoo Assembly cookbook has been written in 2018 and is at this point somewhat outdated (e.g. no phasing at all in the cookbook). Because of the cookbook many still use the older version associated with the main branch. The core assembly functionality has not changed except for we removed the diploid workflow, but there are a few convenience things that make the newer version potentially worthwhile even without phasing. E.g. the whole build-gapped-map part is gone, substituted for building a proper sandboxed map for a given subset of scaffolds. The FINAL suffix is now a HiC suffix. Once you run the default, you should get a .rawchrom.hic and .rawchrom.assembly - the files that you typically want to review in JBAT. After you are done with the manual review, you run the run-asm-pipeline.sh -r <rawchrom.review.assembly> to generate a _HiC.fasta (and optionally a sandboxed _HiC.hic map if you pass a -c flag).

Thanks,
Olga

**Comment by dustin-cram** [comment]
Excellent, thanks so much for the quick response.

It sounds like the output I have is what I should have and I can move forward with JBAT.

**Comment by jiyonghao-cpu** [comment]
> 您好 Dustin，
> 
> 有效的问题。您使用的版本是最新版本，与 Hoencamp 等人在 2021 年科学论文以及我们在 DNA Zoo 内部运行的内容相关。确实，版本控制令人困惑。我对此表示歉意：由于此版本的编辑主要涉及阶段划分部分，因此汇编脚本本身自 2019 年 7 月以来就没有改变过（因此190716）。基本上，脚本的不同部分都有自己的版本跟踪，我应该清理一下。DNA Zoo Assembly 食谱写于 2018 年，目前有些过时（例如，食谱中根本没有阶段划分）。由于说明书的原因，许多人仍然使用与 main 分支关联的旧版本。核心组装功能没有改变，除了我们删除了二倍体工作流程外，但即使没有阶段性，也有一些便利的事情使新版本可能值得。例如，整个 build-gapped-map 部分都消失了，取而代之的是为给定的脚手架子集构建适当的沙盒 map。FINAL 后缀现在是 HiC 后缀。运行默认值后，您应该获得 .rawchrom.hic 和 .rawchrom.assembly - 您通常想在 JBAT 中查看的文件。完成手动审核后，运行 run-asm-pipeline.sh -r <rawchrom.review.assembly> 以生成 _HiC.fasta（如果传递 -c 标志，还可以选择沙盒化 _HiC.hic 映射）。
> 
> 谢谢，奥尔加

二倍体组装已经不适用于该软件了吗
